# .github/workflows/pages.yml
# Build & deploy a Jekyll site to GitHub Pages

name: Deploy Jekyll site to Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:   # manual trigger

permissions:
  contents: read
  pages: write
  id-token: write      # required by deploy‑pages

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v4          # ⬆ latest

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'              # Jekyll‑supported
          bundler-cache: true

      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v5   # ⬆ latest

      - name: Build site with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2   # ⬆ uses artifact v4
        with:
          path: _site                            # default output dir

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v2            # current
